### ISSUE TITLE
Feature Request: Add GitHub Actions Support for Release Monitoring

### ISSUE THREAD

**Issue by malston** [malston/release-monitor#1]
# Feature Request: Add GitHub Actions Support for Release Monitoring

## 🚀 Problem Statement
Currently, the release monitor is designed specifically for Concourse CI/CD pipelines. However, many developers use GitHub Actions as their primary CI/CD tool. Adding GitHub Actions support would significantly expand the tool's reach and make it accessible to a much larger audience.

## 💡 Proposed Solution
Create GitHub Actions integration that allows users to easily monitor releases within their workflows. This could be implemented as:

1. **A reusable GitHub Action** that can be published to the GitHub Marketplace
2. **Example workflows** showing different use patterns
3. **Documentation** for GitHub Actions users

## 📝 Example Usage
```yaml
name: Monitor Dependencies
on:
  schedule:
    - cron: '0 */6 * * *'  # Check every 6 hours
  workflow_dispatch:

jobs:
  check-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: malston/release-monitor@v1
        with:
          config: |
            repositories:
              - owner: kubernetes
                repo: kubernetes
              - owner: hashicorp
                repo: terraform
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Process New Releases
        if: steps.monitor.outputs.new-releases-found > 0
        run: |
          echo "Found ${{ steps.monitor.outputs.new-releases-found }} new releases"
          # Create PRs, send notifications, etc.
```

## ✅ Benefits
- **Broader Adoption**: GitHub Actions has millions of users
- **Native Integration**: No need to set up external CI/CD tools  
- **Marketplace Visibility**: Can be discovered in GitHub Marketplace
- **Easy Setup**: Users can add it to their workflows in minutes

## 🛠️ Implementation Ideas
1. Create a `action.yml` file defining the action
2. Build a Docker container or JavaScript action
3. Add GitHub Actions specific examples
4. Update documentation with Actions instructions

## 💭 Additional Context
This would complement the existing Concourse support rather than replace it. The core Python script remains the same, we're just adding another way to consume it.

Would love to hear thoughts from the community on this! Is anyone interested in helping implement this feature?

## 🔗 Related
- Could also consider support for: GitLab CI, Jenkins, CircleCI, etc.
- This could be the first step toward making the tool CI/CD agnostic
