### ISSUE TITLE
Add Minio support for S3 resources in Concourse pipeline

### ISSUE THREAD

**Issue by malston** [malston/release-monitor#6]
### Description
Add support for using Minio (self-hosted S3-compatible storage) as an alternative to AWS S3 in the Concourse pipeline. This would allow users to run the release monitor pipeline with on-premises storage solutions.

### Current Behavior
The pipeline currently uses AWS S3 resources that require:
- AWS S3 buckets
- AWS credentials (access_key_id, secret_access_key)
- AWS region configuration

### Proposed Solution
Enhance the S3 resource configuration to support Minio by:
1. Adding endpoint URL configuration for custom S3-compatible endpoints
2. Making region optional (Minio doesn't require regions)
3. Supporting path-style bucket access (required for some Minio setups)
4. Adding SSL/TLS configuration options

#### Pipeline Changes Required:
- Update monitor-output S3 resource to support Minio endpoint
- Update release-storage S3 resource to support Minio endpoint
- Modify parameter files to include Minio-specific configuration

#### Example Configuration:
```yaml
resources:
  - name: monitor-output
    type: s3
    source:
      endpoint: ((minio_endpoint))  # e.g., http://minio.example.com:9000
      bucket: ((s3_bucket))
      access_key_id: ((minio_access_key))
      secret_access_key: ((minio_secret_key))
      use_ssl: ((minio_use_ssl))
      use_v4: true  # Minio requires v4 signatures
      skip_ssl_verification: ((minio_skip_ssl_verification))
      versioned_file: release-monitor/latest-releases.json
```

### Benefits
- **Self-hosted option**: Organizations can use their existing Minio infrastructure
- **Cost savings**: No AWS S3 costs for storage
- **Data sovereignty**: Keep release data on-premises
- **Development/testing**: Easier local testing with Minio containers

### Testing Requirements
- Test with Minio server (latest version)
- Verify all S3 operations work correctly
- Test with both HTTP and HTTPS endpoints
- Document Minio setup instructions

### Documentation Updates Needed
- Add Minio setup guide to CONCOURSE_DEPLOYMENT.md
- Update parameter examples with Minio configuration
- Add docker-compose.yml example with Minio for local testing

### Acceptance Criteria
- [ ] Pipeline works with Minio endpoint configuration
- [ ] All S3 operations (put, get) function correctly
- [ ] Documentation includes Minio setup instructions
- [ ] Parameter files include Minio examples
- [ ] Integration tests pass with Minio backend

### Additional Context
This feature would make the release monitor more accessible for organizations that cannot or prefer not to use AWS S3, while maintaining compatibility with the existing AWS S3 setup.
